### ISSUE TITLE
Typescript build error

### ISSUE THREAD

**Issue by T-Ph525** [noxonsu/unifactory#108]
TypeScript error in unifactory/src/components/AccountDetails/index.tsx(229,28):
Argument of type 'import("unifactory/node_modules/@types/react-dom/node_modules/@types/react/index").Context<import("unifactory/node_modules/@types/styled-components/index").DefaultTheme>' is not assignable to parameter of type 'React.Context<import("unifactory/node_modules/@types/styled-components/index").DefaultTheme>'.

**Comment by NotEternal** [comment]
What is your NodeJS version? Use 16. Try to remove **node_modules** and **package-lock.json** and reinstall it.

**Comment by T-Ph525** [comment]
yarn run serve works despite the error.
