### ISSUE TITLE
switch copyright for envato users must be free

### ISSUE THREAD

**Issue by noxonsu** [noxonsu/unifactory#167]
нужно еще раз проверить, что файл залитый на кодканьон имеет бесплатное отключение копирайта и там нет фи. так же проверить, что нет нашего фи в https://pipiswap.net/#/swap

**Comment by NotEternal** [comment]
Обновил код, чтобы ВП версия не спрашивала оплату.
Проверил сайт по ссылке, там не стоит наш адрес для комиссии, поэтому она не будет отчисляться.
