### ISSUE TITLE
admin: tokenlist not working

### ISSUE THREAD

**Issue by noxonsu** [noxonsu/unifactory#49]
я добавил в админке лист, но в выпадающих списках по прежнему ничего 
https://screenshots.wpmix.net/chrome_cyrOtnd1eY1feDyXDUmR3pZoKDpGyCdl.png
 https://alo1.onout.xyz/

сюдаже: наверное надо делать fetch options когда админ переходит на вкладку, а то мне предложили опять его создать (но просто не подгрузилось)

**Comment by NotEternal** [comment]
с листами проблемы нет. Проблема с названиями. Мы перед тем как лист добавлять, проверяем его структуру по схеме юнисвапа. Если есть проблемы, то не добавляем его. Тут в символах проблема:
![image](https://user-images.githubusercontent.com/61930014/150341213-2050d057-174c-4d69-af5a-ed9e1130a314.png)

**Comment by noxonsu** [comment]
Тогда пока ок.

чт, 20 янв. 2022 г. в 15:46, NotEternal ***@***.***>:

**Comment by NotEternal** [comment]
удалил все что связанно с ручными запросами. Сейчас на загрузке приложения видно, есть данные или нет. Если есть, то  сразу их из стейта используем
