### ISSUE TITLE
add copyright

### ISSUE THREAD

**Issue by noxonsu** [noxonsu/unifactory#66]
добавить неубиваемую ссылку в бесплатную версию "powered by OnOut - `<a href="https://tools.onout.org/dex">no-code tool for creating DEX</a>`"

> добавить опцию для отображения ссылки и по умолчанию сделать видимой

- [x] понять как отличить бесплатную от платной, видимо флаг в регистри, по умолчанию бесплатная.

**Comment by NotEternal** [comment]
регистри надо менять, заного деплоить и данные перенести с прошлых контрактов.
То есть лучше как-то по другому

**Comment by NotEternal** [comment]
можно смотреть если есть Wordpress данные, значит платный плагин. Не показывать ссылку в этом случае.
Но пока не ясно как это делать с кастомной сборкой
